const products = [
    {
        id: 1,
        title: "goggle-pixel9",
        price: 38999,
        description: "goggle-pixel9",
        category: "mobiles",
        image: "images/goggle-pixel9.png",
    },
    {
        id: 2,
        title: "apple-thunderbolt-27",
        price: 222999,
        description: "monitor",
        category: "Electronics",
        image: "images/apple-thunderbolt-27.png",
    },
    {
        id: 3,
        title: "Haier 1.6 Ton 4 Star AI Smart AC - HSU19K-PYAIR4BN-INV",
        price: 22999,
        description: "ac",
        category: "Electronics",
        image: "images/Haier 1.6 Ton 4 Star AI Smart AC - HSU19K-PYAIR4BN-INV.png",
    },
    {
        id: 4,
        title: "headphone",
        price: 1599,
        title: "headphone",
        description: "headphone",
        category: "Electronics",
        image: "images/headphone.png",
    },
    {
        id: 5,
        title: "puma-shoes",
        price: 12499,
        description: "Comfortable to walk easy to run",
        category: "Footwear",
        image: "images/puma-shoes.png",
    },
    {
        id: 6,
        title: "iphone15",
        price: 65999,
        description: "iphone 15 128 GB storage ",
        category: "Electronics",
        image: "images/iphone15.png",
    },
    {
        id: 7,
        title: "Mast & Harbour Men's Standard Opaque Checked Casual Shirt",
        price: 899,
        description: " Casual Shirt ",
        category: "fashion",
        image: "images/Mast & Harbour Men's Standard Opaque Checked Casual Shirt.png",
    },
    {
        id: 8,
        title: "smartwatch",
        price: 1699,
        description: " smartwatch ",
        category: "electronics/fashion",
        image: "images/smartwatch.png",
    },
    {
        id: 9,
        title: "T-shirt",
        price: 699,
        description: " T-shirt ",
        category: "electronics/fashion",
        image: "images/T-shirt.png",
    },
    {
        id: 10,
        title: "nike-sliders-men",
        price: 2599,
        description: " nike-sliders-men ",
        category: "fashion",
        image: "images/nike-sliders-men.png",
    },
    {
        id: 11,
        title: "samsung-refregirator",
        price: 2599,
        description: "refregirator ",
        category: "electronic",
        image: "images/samsung-refregirator.png",
    },
    {
        id: 12,
        title: "laptop",
        price: 32999,
        description: "laptop ",
        category: "electronic",
        image: "images/laptop.png",
    },
];